### ISSUE TITLE
Unsupported Encryption Algorithm

### ISSUE THREAD

**Issue by shumailaahmed** [kimci86/bkcrack#102]
I am trying to decrypt the password to file encrypted using 7zip

```
Path = test.wav
Folder = -
Size = 175542316
Packed Size = 109707880
Modified = 2021-10-24 16:21:54
Created = 2021-10-24 16:21:53
Accessed = 2021-10-25 15:43:01
Attributes = A
Encrypted = +
Comment = 
CRC = 
Method = AES-256 LZMA:EOS
Host OS = FAT
Version = 63
Volume Index = 0
```

There is no CRC, 

when run 

`bkcrack -C  test.zip -c test.wav -p plain.wav -x -1 00`

I get 

```
bkcrack 1.5.0 - 2022-07-07
Zip error: entry "test.wav" is encrypted with an unsupported algorithm.
```

Any insights on this will be valuable

**Comment by kimci86** [comment]
Your encrypted ZIP file is using AES encryption. This encryption algorithm is not subject to Biham and Kocher's known plaintext attack so bkcrack refuses to use it. Only traditional encryption also known as ZipCrypto can be used with bkcrack.

So in your case bkcrack will not be helpful. You can try password cracking with other tools such as [hashcat](https://hashcat.net/hashcat/) or [john the ripper](https://www.openwall.com/john/).

**Comment by shumailaahmed** [comment]
Yes John worked like a charm, was trying out Bcrack for different use cases

**Comment by kimci86** [comment]
I understand your question is answered so I close this issue. Feel free to reopen or open other issues if you have questions or suggestions.
