### ISSUE TITLE
Question about attacking deflate compression with partial plaintext

### ISSUE THREAD

**Issue by xinhuang** [kimci86/bkcrack#103]
Hi,

First of all thank you for creating this wonderful tool.

I am working on a CTF challenge, and one of the zip file contains a deflate file of .DS_Store, of which the header (first 20-22 bytes) is somewhat fixed. So I think it's vulnerable to CPA.

However, after reading Issue #49 and based on the zip file I created by myself, I cannot successfully carry out the attack and find the key. (I did solve one challenge without deflate compression, as well as reproduced Issue #49, though)

From below inspection, it seems in Issue #49, the deflated sequence of partial plaintext matches the deflated full plaintext; but for .DS_Store, the deflated sequence of partial plaintext, DS_Store.0 file, doesn't match the deflated squence of the .DS_Store file.

Is this the reason why the attack fails? Can anyone please shed some light on how to carry the CPA attack in this case?

Thank you!

```
$ echo -n 'TOP SECRET! 111111111111111111111' | python3 deflate.py| xxd
00000000: 0bf1 0f50 0876 750e 720d 5154 30c4 0600  ...P.vu.r.QT0...

$ echo -n 'TOP SECRET! ' | python3 ../deflate.py | xxd
00000000: 0bf1 0f50 0876 750e 720d 5154 0000       ...P.vu.r.QT..


$ xxd DS_Store.0 
00000000: 0000 0001 4275 6431 0000 1000 0000 0800  ....Bud1........
00000010: 0000 1000                                ....

$ xxd ../.DS_Store | head -n 2
00000000: 0000 0001 4275 6431 0000 1000 0000 0800  ....Bud1........
00000010: 0000 1000 0000 040a 0000 0000 0000 0000  ................

$ python3 ../deflate.py -l 4 < DS_Store.0 | xxd
00000000: 6360 6060 742a 4d31 6460 1060 6060 e060  c```t*M1d`.```.`
00000010: 00d1 00                                  ...

$ python3 ../deflate.py -l 4 < ../.DS_Store | xxd | head -n 2
00000000: ed98 df4b 0241 10c7 67d4 d44b 021f 0a22  ...K.A..g..K..."
00000010: 080e 7ab5 f247 14d1 8b99 41bd f490 520f  ..z..G....A...R.
```

The command I ran is:
```
$ ./bkcrack -c .DS_Store -C test.zip -P tmp/plain.zip -p DS_Store.0 -t 12

$ ./bkcrack -L test.zip 
bkcrack 1.5.0 - 2023-08-07
Archive: test.zip
Index Encryption Compression CRC32    Uncompressed  Packed size Name
----- ---------- ----------- -------- ------------ ------------ ----------------
    0 ZipCrypto  Deflate     8325d75e         6148          455 .DS_Store

$ ./bkcrack -L tmp/plain.zip 
bkcrack 1.5.0 - 2023-08-07
Archive: tmp/plain.zip
Index Encryption Compression CRC32    Uncompressed  Packed size Name
----- ---------- ----------- -------- ------------ ------------ ----------------
    0 None       Deflate     dad7c23c           20           19 DS_Store.0
```

Here is the base64 encoded test.zip (compression using zip 3.0 with level 4 on Ubuntu 20.04 LTS, password is 123)
```
UEsDBBQACQAIAG2NClde1yWDxwEAAAQYAAAJABwALkRTX1N0b3JlVVQJAAMto9RkPqPUZHV4CwABBOoDAAAE6gMAAKHX91G2hzkZNaqyYLwNN9lhgCdeU96NWb5cDq89LgClMlChhjsBiVkV5nanTt3ZIdvsb5x+QxPIW/a3ljDofFAB2Ie1zcRc4m17lP6F6LZko55df/8Mga7vQ1vIr5BU5JGY+Cqd0LeKycrYt49WNH2jXVYaHWhE89Gh3NLHh84GK3GrEMq9x9CcSv+SAqmrrW2MPV28JfIZY+yIqFnUSjPPGw+17pUGjWxt2dnI0Umb9jw/3CGOtYYwUkLYgDWvS1iy3Oc9+PmUtBqSJbp/RJ7Cj4or+/YI/oE91/bUxLbHOSlV4A8kiezjKTUmcz9k+hGYm7ZGUJDBAB9aNKEyc9CFnMxMIqJ60Tmedw47ys43lvVIw1B7CHHL25zBj1LqkoZI8N/1Vji3B9cGqfWMe8nNbTCH51d/4GqDrXuOuqZziv4iN/PWI/8b5tnEq6MyIY8txdDaXYNtBRXHhEifk536aMS3cTCPA4KzXGkPShiEzCIKcYcKYuh2P8FeIbx7lNEE9jC/I2Embql+FyRvakhD9KXQa94n6byQTKZ0bOJ9s8uunYvCl5wiuVD2SeVFPV2QNP3MyMjjRysUsO/kFlpHjzV+Dxf/UEsHCF7XJYPHAQAABBgAAFBLAQIeAxQACQAIAG2NClde1yWDxwEAAAQYAAAJABgAAAAAAAAAAACkgQAAAAAuRFNfU3RvcmVVVAUAAy2j1GR1eAsAAQTqAwAABOoDAABQSwUGAAAAAAEAAQBPAAAAGgIAAAAA
```
 and here is the base64 encoded header of the .DS_Store file:
```
AAAAAUJ1ZDEAABAAAAAIAAAAEAA=
```

**Comment by kimci86** [comment]
Hi,

As you understood, compressing a file prefix is not the same as taking the prefix of a compressed file in general.

In this case, the file is large enough for deflate compression to build a huffman tree to model the data. This statistical model is put at the beginning of deflate output. Getting a correct prefix of the compressed file would require guessing the huffman tree which is hard without having a large part of the file.

However, we can hope that compressing another similar full `.DS_Store` file could give similar compressed data.
It turns out it is the case. Using compressed data from `../.DS_Store` file you shared above:  

    bkcrack -C test.zip -c .DS_Store -x 0 ed98df4b024110c767d4d44b021f0a22080e7ab5f24714d18b9941bdf490520f

quickly give the solution.

We can then also recover the password with bkcrack which gives "123".
Bruteforce password cracking would have been worth trying first :)

**Comment by xinhuang** [comment]
Thank you for the answer. Now I know why the attack failed. Maybe I need to find some more .DS_Store samples and try it with the attack.
