### ISSUE TITLE
Add donation information to readme

### ISSUE THREAD

**Issue by kimci86** [kimci86/bkcrack#107]
> It would be great if you add a contribution possibility in the readme :)

_Originally posted by @navy3dfx in https://github.com/kimci86/bkcrack/issues/106#issuecomment-1689079407_

Hi @navy3dfx, thank you for the feedback. Could you elaborate about what you think could be added to the readme?

**Comment by navy3dfx** [comment]
Hi, I thought that it would have been nice to have something like a donation link for anyone who might want to support the project.

**Comment by kimci86** [comment]
Thank you for the suggestion. I set up my GitHub Sponsors profile and wait for staff approval.

**Comment by kimci86** [comment]
My GitHub Sponsors profile was approved last week. I just added related information to the readme.
