### ISSUE TITLE
Full-archive decryption

### ISSUE THREAD

**Issue by kimci86** [kimci86/bkcrack#12]
Remove encryption of a full archive instead of deciphering a single zip entry.

**Comment by Arnie97** [comment]
I have lots of deeply nested subdirectories in my zip archives, so I wrote a python script for the trivial task:
https://gist.github.com/Arnie97/249c4846cf9025e2e0356307d9f17e80
Hope this helps.

**Comment by kimci86** [comment]
Thank you for sharing your solution.

**Comment by kimci86** [comment]
Note for myself: a solution is to set the password to some given string.
It is easier to implement as there is no need to edit file headers.

**Comment by kimci86** [comment]
In the meantime, another solution is given with [Aloxaf's patched p7zip](https://github.com/Aloxaf/p7zip) as pointed out in https://github.com/kimci86/bkcrack/issues/27#issuecomment-803513802.
