### ISSUE TITLE
How  to crack a ZipCrypto deflate archive with an dll?

### ISSUE THREAD

**Issue by forwgzz** [kimci86/bkcrack#122]
DLL files all have the same header bytes

```
0000000: 4d5a 9000 0300 0000 0400 0000 ffff 0000  MZ..............
0000010: b800 0000 0000 0000 4000 0000 0000 0000  ........@.......
0000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
0000030: 0000 0000 0000 0000 0000 0000 8000 0000  ................
0000040: 0e1f ba0e 00b4 09cd 21b8 014c cd21 5468  ........!..L.!Th
0000050: 6973 2070 726f 6772 616d 2063 616e 6e6f  is program canno
0000060: 7420 6265 2072 756e 2069 6e20 444f 5320  t be run in DOS
0000070: 6d6f 6465
```

I am trying to use these bytes and compressed these bytes as plaintext,but it cannot get key.

How can I get keys by these bytes? Can you help me?
this is test file:temp.zip,password,123456789
[file.zip](https://github.com/user-attachments/files/15799122/file.zip)

**Comment by kimci86** [comment]
This header alone is not enough in your case. Deflate compression works by finding repetition and building a statistical model on bigger blocks of data (e.g. a few dozens of kilobytes). Compressing a small prefix will not give a prefix of the compressed data.

I would suggest focusing on other files in your archive for which it might be easier to get known plaintext: either uncompressed files with known file format, or files that you can find entirely somewhere else so they can be compressed correctly.

Let me know if it helps.

**Comment by forwgzz** [comment]
Thank you, I will try other files
