### ISSUE TITLE
If the name has contain any space then it will throw an error 

### ISSUE THREAD

**Issue by sachin6216** [kimci86/bkcrack#129]
<img width="1203" alt="Screenshot 2024-08-01 at 15 25 12" src="https://github.com/user-attachments/assets/d832a14b-042b-4f08-af17-24f60c4c607c">

**Comment by kimci86** [comment]
You can put quotes around arguments that contain spaces or use an escape sequence starting with backslash. Otherwise it will be treated as separate arguments by your command line interpreter.

In this example:

    bkcrack -C /Users/mac/Downloads/project.zip -c "Delhi project/IMG_20220828_025758.jpg" -p plain.txt

or

    bkcrack -C /Users/mac/Downloads/project.zip -c Delhi\ project/IMG_20220828_025758.jpg -p plain.txt
