### ISSUE TITLE
Is it practically impossible to crack a deflated file from a few header bytes?

### ISSUE THREAD

**Issue by L4cache** [kimci86/bkcrack#136]
I was trying to crack some zipped mp4 video files. For stored files this works, but for deflated files, I have no success.
I think it's because the window used in deflate is usually much bigger (longer) than the format magic bytes, this will make the deflated text dependant on next - probably a few thousand - bytes, and the plain text is practically impossible to "construct" from just a few magic bytes.
Am I right?

**Comment by kimci86** [comment]
Yes in general this is right.
There are some cases where deflate compression outputs a stored block at the beginning or at the end of the deflate stream, which can make cracking easier, but in general we need to compress a big chunk of the file to get correct compressed data.

**Comment by kimci86** [comment]
I am assuming the question is answered so I close this issue.
