### ISSUE TITLE
Is it possible to use wildcards in plaintext?

### ISSUE THREAD

**Issue by Zapeth** [kimci86/bkcrack#14]
The readme specifies `contiguous plaintext`, but I was wondering/hoping if this attack could also be applied for a plaintext where 1-2 bytes are "skipped".

For example I have a cipher where the first 10 bytes are known, followed by 2 unknown, 2 more known and the rest of the data.

Would it be somehow possible to "stitch" these known bytes together to satisfy the conditions for a successful attack?

**Comment by kimci86** [comment]
Hello, I have been thinking about this for a while. I believe an approach is possible where 12 known bytes are needed, but only 8 are required to be contiguous. However, this approach is not implemented.

**Comment by kimci86** [comment]
I add this for my future self who will implement it:

The approach requires 12 known plaintext bytes of which only 8 must be contiguous:
- Generate (on average) 2^32 possible internal keys using 8 contiguous plaintext bytes.
- To filter out candidates, decrypt ciphertext forward and backward and compare the result with 4 other known plaintext bytes.

The 4 bytes used for filtering could even come from other zip entries (in particular the CRC byte), but the more spread out the byte offsets are, the slower the attack would be I guess.

**Comment by Zapeth** [comment]
Interesting, that would certainly be helpful for those cases where just barely enough is known about the decrypted data.

Unfortunately it still wouldn't quite apply to my use case, since I can only group the known bytes 10 by 2. There are more known byte chunks in my cipher but I don't know their offset in the decrypted data (there might be 2 more bytes I could use, but I'm guessing the 4 bytes also need to be contiguous?).

Aside from that, do you know yet if your approach will have certain limitations? Like do the 4 bytes need to be different to the 8 bytes, or can they only be within a certain byte range for this to work?

**Comment by kimci86** [comment]
If I understand correctly your case, you know that plaintext at some known offset has the pattern `XXXXXXXXXX??XX` where `X` means a known byte and `?` an unknown byte.
Then, the approach I am thinking of could be used. The first 8 known bytes (which are contiguous) can be used to generate candidates and the remaining 4 bytes can be used for filtering. There are no constraints on those 4 bytes. They can be at any known offset (contiguous or not) and have any value.

I hope I will find some time to implement it soon enough. (It might take a while.)

**Comment by Zapeth** [comment]
Thats great to hear, I'm looking forward to try it out.

In regards to usage, your example with the pattern indicating which bytes are (un)known is probably the easiest to use already (unless the 4 remaining bytes are further apart).

Alternatively a size specifier could be used that would alternate between known and unknown byte sizes in the given plaintext.

If the 4 bytes can be really split up in just single bytes then a worst case example would be `8:5:1:3:1:2:1:7`, which translates to a pattern of `XXXXXXXX?????X???X??X???????X` (size of last one is implied by EOF).

Or in my case just `10:2`, where the 10 bytes would be automatically split in 8+2 because the plaintext contains only 12 known bytes in total.

But thats just my random thoughts, maybe you already have an implementation in mind, so feel free to use whatever you prefer.

**Comment by kimci86** [comment]
Hello, I was faster than I expected to implement the approach. An implementation is available in the branch `non-contiguous`.
I tested the implementation on one example and it worked well. (It even had better performance than the traditional approach, contrary to what I expected.)

Regarding usage, I chose to pass the non-contiguous bytes of plaintext as command line arguments with the `-x` flag, giving pairs of offsets and hexadecimal strings. It seems acceptable to me because at most 4 bytes are needed.
Example: `bkcrack -C archive.zip -c file -p plaintext -x 14 3a2d -x 17 44`

Please let me know how it goes when you try it out.

**Comment by Zapeth** [comment]
It turned out that my aforementioned 10-2 known byte assumptions were wrong, but I was able to use 8-4*1 bytes instead (also tried it with a test file before that to be sure).

So yeah, had no issues using it, great work and thanks for implementing it so soon after my inquiry :)

**Comment by kimci86** [comment]
Great! Glad it worked.
I will close this issue when I merge the branch.
