### ISSUE TITLE
No CRC data in zip archives

### ISSUE THREAD

**Issue by NanoQuad** [kimci86/bkcrack#17]
If you zip files with 7-zip  (19.00) or Winzip (output format *.zip) there is no CRC-data inside the enrypted archive and bkcrack couldnt extract the keys.

What i´m done:
I encrypted the example file with the tutorial and put it in a new encrypted encrypted.zip archiv.

**Comment by kimci86** [comment]
Hello, could you detail the steps to reproduce this experiment?
Looking at 7-zip 19 source code, I can confirm the CRC's most significant byte is written at the end in the encryption header when using ZipCrypto.
Probably the plaintext you provided was not correct.

**Comment by NanoQuad** [comment]
Hello,
I extracted the 2 files from your example, and put it to a new *.zip-archiv (with 7-zip standard configuration) and a new password.

If i open your zip-file with 7zip i can see data under the CRC-Tab, but in my zip-archiv the tab is blank.

I run your programm with the same data from the example at my new archiv (with obly your 2 files) bit it couldnt extract the 3 keys.

Best regrad from south germany
Stefan



Von meinem iPhone gesendet

**Comment by kimci86** [comment]
Ok, in this case the files are both compressed before encryption whereas the svg file in my example archive is only stored before encryption.
In addition, if the CRC are not visible, I suspect AES encryption was used, which is a stronger alternative to ZipCrypto that bkcrack can not attack.
You can see what compression or encryption method is used by running the command `7z l -slt encrypted.zip`

**Comment by kimci86** [comment]
Do you need more help? I will close this issue otherwise.

**Comment by NanoQuad** [comment]
No thanks, you can close the issue.
Best regrads feom germany

Von meinem iPhone gesendet
