### ISSUE TITLE
Find password from master keys

### ISSUE THREAD

**Issue by libjet** [kimci86/bkcrack#19]
Something akin to pkcrack's "findkey" program, but using a faster process and supporting more varied password lengths would be great.

**Comment by kimci86** [comment]
Hi, thank you for the suggestion.
I have been thinking about it too. I will eventually give it a try, but it will probably not do better than hashcat.
This was added to hashcat last year (See https://github.com/hashcat/hashcat/pull/2032)

**Comment by libjet** [comment]
I noticed hashcat's mode and have been using it, but I noticed that findkey is CPU only (and single threaded at that), and completed a 10 character search much faster than my RX 480 could through hashcat. Because the program is the same speed regardless of character length, above 10 characters is unbearably slow and so if there's any way to overcome this problem then I think it would become a much more efficient way to crack PKZIP master keys.

**Comment by Aloxaf** [comment]
You can try AZPR. It's really fast in finding the password.

**Comment by kimci86** [comment]
It is now implemented. It is much faster than pkcrack's "findkey" thanks to a little improvement to the algorithm which allows to discard candidates early.

Here is a small benchmark on my machine:
- pkcrack's findkey
  - 10 bytes (range 0 - 255) or less: 3 min 40 s
- bkcrack v1.3.0
  - 10 bytes (range 0 - 255) or less: 23 s (1 thread), 5,5 s (8 threads)
  - 12 ASCII printable characters or less: 7 min 7 s (8 threads)
  - 12 alphanumeric characters or less: 22 s (8 threads)
