### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by rifl3man1** [kimci86/bkcrack#21]
hello! im trying build exe with visual studio 2019 but get errors. bkcrack.exe not appears in project folder

**Comment by kimci86** [comment]
Hello, I suggest not using Microsoft's compiler as it does not support recent versions of OpenMP (used for parallelization). You can try with either GCC or clang compiler.

**Comment by kimci86** [comment]
I made small changes in my last commit (see https://github.com/kimci86/bkcrack/commit/01d93eba549dbda4451672973e54214c2672550c) so you can use visual studio to compile the project.
Does it solve your issue?

**Comment by kimci86** [comment]
In addition, precompiled packages are now available. See [releases](https://github.com/kimci86/bkcrack/releases). I therefore consider that this issue is solved.
Thank you for your interest.

**Comment by rifl3man1** [comment]
thank you
