### ISSUE TITLE
Not responding when opening non-zip file

### ISSUE THREAD

**Issue by xhtechxposed** [kimci86/bkcrack#22]
![image](https://user-images.githubusercontent.com/74121287/98454180-926a8000-219c-11eb-81dc-f22418b33a27.png)
i used crack 7z file but always have response。why？less file have response，but more file 7z don't have response

**Comment by kimci86** [comment]
Sorry, I do not understand. Could you describe your problem with more details?

**Comment by xhtechxposed** [comment]
my file is large，so not response ，how to fix ，my file is 100M

**Comment by kimci86** [comment]
Ok, I understand.
You have 7z files but bkcrack works only with zip files. It is stuck in a loop looking for a signature used in the zip format. In addition, it is not using the same encryption method so the attack cannot work anyways.

You might want to try a bruteforce or dictionary attack with [john the ripper](https://www.openwall.com/john/) or [hashcat](https://hashcat.net/hashcat/).

**Comment by xhtechxposed** [comment]
ok
