### ISSUE TITLE
How to recover the original files if they are in a folder insider the zip file

### ISSUE THREAD

**Issue by yudonglin** [kimci86/bkcrack#27]
So let's say we have a zip file like this

1.zip
- Folder11test
- - data1
- - data2

So right now, I have the key. What will the command look like if I want to recover data1 (which is in the "Folder11test" folder)?
Thank you!!

**Comment by kimci86** [comment]
Hello,
You have to prepend `Folder11test/` to the filenames. This should work from the installation folder:
```
./bkcrack -C 1.zip -c Folder11test/data1 -d data1 -k <X> <Y> <Z>
```
If deflate compression was used, decompress:
```
python3 tools/inflate.py < data1 > data1_decompressed
```
Do the same for `data2`.

**Comment by cxzstuff** [comment]
Easiest way is maybe Aloxaf's custom p7zip for Linux
https://github.com/Aloxaf/p7zip

I compiled a Win32 version, which can be found from here: 
https://forum.xda-developers.com/t/file-encrypted-how-can-i-open-it-help.4194779/page-9#post-84683229

**Comment by kimci86** [comment]
With bkcrack version 1.2 and up, it is also possible to transform an encrypted archive to the change to password.

    bkcrack -C encrypted.zip -k 12345678 23456789 34567890 -U unlocked.zip password

Then, you can extract files with any zip file manager and the chosen password.
I consider this question answered. Feel free to reopen if you need more help.
