### ISSUE TITLE
A bug, a key is missing the first character

### ISSUE THREAD

**Issue by cxzstuff** [kimci86/bkcrack#29]
Hi,

Found a bug I think.
Bkcrack's out put is below.
The keys outputted:  dd6c17f1  402a80f 900cf09e
The keys should be:  dd6c17f1 0402a80f 900cf09e
As one can see there is a place for that zero, but it's missing.
The deciphered text is written though...

```
bkcrack 1.0.1 - 2021-03-15
Generated 4194304 Z values.
[13:01:03] Z reduction using 192 bytes of known plaintext
100.0 % (192 / 192)
44384 values remaining.
[13:01:05] Attack on 44384 Z values at index 8
Keys: dd6c17f1  402a80f 900cf09e
62.5 % (27723 / 44384)
[13:01:56] Keys
dd6c17f1  402a80f 900cf09e
Wrote deciphered text.
```

**Comment by kimci86** [comment]
Hello,
The keys are just numbers, so zeros on the left are not significant.
But I agree it can look surprising not to show them. I will change that.
Thank you for this suggestion.
