### ISSUE TITLE
Deciphering works when cracking but not when using the keys directly

### ISSUE THREAD

**Issue by kimci86** [kimci86/bkcrack#30]
Hi @cxzstuff, you wrote on [XDA Developers Forums][1]:
> Extracted or deciphered ok after cracking, but not when using the keys.

Could you give more information to help me investigate this?
What commands and data (if not confidential) did you use? Thank you.

[1]: https://forum.xda-developers.com/t/file-encrypted-how-can-i-open-it-help.4194779/page-9#post-84697607

**Comment by cxzstuff** [comment]
> Hi @cxzstuff, you wrote on [XDA Developers Forums](https://forum.xda-developers.com/t/file-encrypted-how-can-i-open-it-help.4194779/page-9#post-84697607):
> 
> > Extracted or deciphered ok after cracking, but not when using the keys.
> 
> Could you give more information to help me investigate this?
> What commands and data (if not confidential) did you use? Thank you.

Could not repeat it now, so maybe I just made a typo. Added that info to the post at xda.

**Comment by kimci86** [comment]
Ok, so I guess I can close this issue. Do not hesitate to report any problem you have using bkcrack or ask for help.
Thank you for your feedback.
