### ISSUE TITLE
Need help - Error message: "File error: The input file plain.zip could not be opened."

### ISSUE THREAD

**Issue by Jeffrey2705** [kimci86/bkcrack#31]
Hello,

I always get the following error with the test files:
File error: The input file plain.zip could not be opened.

Command:
F:\Downloads\Test\bkcrack -C encrypted.zip -c SomeXmlFile.xml -P plain.zip -p plain.txt
I open CMD via Administrator.

Source: https://blog.devolutions.net/2020/08/why-you-should-never-use-zipcrypto
Even if I create the file myself with 7-zip, I get the same error message.

What am I doing wrong?

**Comment by kimci86** [comment]
Hello, it is probably because your file `plain.zip` is not is the same folder as the bkcrack executable. You can either move your zip file in the Test directory where bkcrack is or pass relative or absolute paths on the command line.

**Comment by Jeffrey2705** [comment]
Hi Kimci,

thank you for the answer.
The files are in the working directory, yet I get the same error message:

![Ordnerstruktur](https://user-images.githubusercontent.com/83613275/117055699-bb1e9d00-ad1b-11eb-9655-c66ed3d7f554.jpg)

Command:
F:\Downloads\Test\bkcrack-1.2.2-win64\bkcrack.exe -C .encrypted.zip -c SomeXmlFile.xml  -P .plain.zip -p .plain.txt

If I enter the absolute path, I get the message:

> Zip error: found no entry F:\Downloads\Test\bkcrack-1.2.2-win64\plain.txt in archive F:\Downloads\Test\bkcrack-1.2.2-win64\plain.zip.

Command:
F:\Downloads\Test\bkcrack-1.2.2-win64\bkcrack.exe -C F:\Downloads\Test\bkcrack-1.2.2-win64\encrypted.zip -c SomeXmlFile.xml  -P F:\Downloads\Test\bkcrack-1.2.2-win64\plain.zip -p F:\Downloads\Test\bkcrack-1.2.2-win64\plain.txt

plain.txt is however included:
![Plan zip](https://user-images.githubusercontent.com/83613275/117056491-a42c7a80-ad1c-11eb-8ddb-fdcb13b39df9.jpg)

**Comment by Jeffrey2705** [comment]
ok, seems to work now after a reboot, thanks

**Comment by kimci86** [comment]
Good! I close this issue then.

To explain a bit more and for others who might have the same question:

-C and -P parameters expect filenames. Filenames can be absolute or relative. If a filename is relative, it is relative to your working directory. You can change your working directory using the `cd` command in your terminal.

Then, the -p and -c parameters expect entry names inside the zip files. It does not depend on your working directory.
(Note that if you use -p or -c alone, i.e. without -C or -P, then filenames are expected and not entry names.)
