### ISSUE TITLE
Issue with decrypting archive containing only deflated files

### ISSUE THREAD

**Issue by Connor-Corp** [kimci86/bkcrack#32]
Hi there, love the tool, but I’m having a bit of an issue with running it on my own zip archive.

The zip archive contains the following:

-A main folder 

-One ReadMe.txt file (Encrypted) inside the folder

-One Executable file (Encrypted) inside the folder

Known facts about the archive:

-Ten character password (Unknown KeySpace)

-Identical decryption key for both encrypted files 

-ZipCrypto, the same version used for the example zip file

-Both files are deflated

-Major sections of the ReadMe.txt file are known

The issue:

I took the same approach to cracking the key like the tutorial. I ran both the tutorial and my own file through Zip2John and found both are PKZIP2, which told me that it’s most likely vulnerable. I started with finding the CRC of the TXT file, which was 7E...., so I assumed that I could just plug-in 7E for the offset at the end of the command. Then I used the echo command to create a file of the characters I knew were inside of the TXT file. After that I ran the script, and it began trying to break the encryption, however it ended with no key found. 

What I believe to be the issue:

Both files are deflated, meaning that there might be a chance the offset is invalid and thus the tool won’t work. I believe the compression method is just default zip compression, and ZipCrypto suggests zipping with either the default windows utility or 7Zip with specific settings.

Can you assist me with this? I think this is a really interesting cryptographic attack but it just doesn’t seem to want to work for me which is quite annoying.

**Comment by Connor-Corp** [comment]
Oh yeah, just to append to this. I took a look into fully reconstructing the ReadMe.txt file in unencrypted form, and got the correct uncompressed size of 280 bytes. Great, right? Well there's an issue. Compressing it always causes 1 byte to be lost. I'm positive my reconstruction is at least 98% accurate, but would a 1 byte loss mean an impossibility with this attack?

**Comment by kimci86** [comment]
Hello!
From the information you give, I think we should be able to make it work.
Could you share the compressed and uncompressed sizes of this readme.txt file?
If it is not confidential, could you also share the known uncompressed content and the CRC for this file from the zip archive?
Maybe if very little data is missing, we can try to guess it and use the CRC as a way to validate our guessing.
Then, trying different compression levels and archive managers to get the same compressed size should give good known compressed data for an attack.

**Comment by Connor-Corp** [comment]
Sure! Thanks for the reply. I actually did some more messing around and managed to get something interesting. I believe I was able to reconstruct the ReadMe.txt file 100%, and figured out the zipping parameters. It used Winrar's "Fast" compression algorithm with a 32kb dictionary size, and legacy zip encryption. The CRC checksum, byte count, and compression information was identical, but the offset was off. The files should be hosted on a repository of mine, in a nice zip package for you.

**Comment by Connor-Corp** [comment]
Very interesting. Now my goal is to get the executable, so with the very last command, I would just change it to point to the executable or not?

**Comment by kimci86** [comment]
You are welcome.
Recovering the password is not implemented yet. It was requested already in #19 and I started to work on it recently. I should release it in not too long.
You can also try hashcat which implements this on the GPU.
However, I tried to recover the password for your case with both hashcat and my prototype and I found no solutions of 10 bytes or less. It is probably longer. If you really need it, it will take a while to find.

**Comment by kimci86** [comment]
Yes, it is not trivial, but faster than directly bruteforcing it.
Using the master key, recovering the password is similar to bruteforcing n-6 characters where n is the password length, i.e. 6 characters are given almost instantly by the master key. The time still grows exponentially with the length.

**Comment by Connor-Corp** [comment]
Perfect. Thank you for the support!
