### ISSUE TITLE
Resuming a cancelled password recovery ?

### ISSUE THREAD

**Issue by cxzstuff** [kimci86/bkcrack#35]
If one cancels the recovery, bkcrack now starts from the beginning.  It would be nice if recovery could be resumed...

**Comment by cxzstuff** [comment]
Got a password, correct but not correct. How about continuing the recovery even if a password is found?
Has the correct one the same length?
https://forum.xda-developers.com/t/file-encrypted-how-can-i-open-it-help.4194779/post-85091353

**Comment by kimci86** [comment]
>  Has the correct one the same length?

Not necessarily.

> How about continuing the recovery even if a password is found?

I will also work on that, it was requested yesterday in #34.

**Comment by cxzstuff** [comment]
Pkcrack has this possibility, or its tool findkey. Haven't tested it. 
findkey key0 key1 key2 pwdlen initvalue

**Comment by kimci86** [comment]
It is now possible to resume an interrupted password recovery.

Example, running this command:
```
bkcrack -k c4490e28 b414a23d 91404b31 --bruteforce ?a --length 12
```
and hitting <kbd>Ctrl</kbd>+<kbd>C</kbd> will print an option to resume the password recovery:
```
[15:10:35] Recovering password
length 12...
33.7 % (1295 / 3844) 
Operation interrupted by user.
You may resume the password recovery with the option: --continue-recovery 4b7342303030
[15:10:36] Could not recover password
```

Then, adding the printed option to the command will resume where it was stopped:
```
bkcrack -k c4490e28 b414a23d 91404b31 --bruteforce ?a --length 12 --continue-recovery 4b7342303030
```
