### ISSUE TITLE
JPEGs...

### ISSUE THREAD

**Issue by RetiefTech** [kimci86/bkcrack#36]
Hi, how would you go about finding the plaintext/cracking of a zip containing a jpeg?
I took a jpeg took from a camera, which embeds EXIF data into the file, then zipped it with a password.
When you open the jpeg you can see the EXIF data, this is the original file name, date taken, camera model etc
So used the original file name as the plaintext to be searched for with the relevant offset etc.

Did return some keys, used that to create a new zip file with another password, when extracting is says the password is incorrect, am using the password specified by the -U option 
Tried the method with the decipherfile and used python to decompress, but got an error with python: 
zlib.error: Error -3 while decompressing data: invalid block type

Any ideas on what I am doing wrong or how else I could approach this?

**Comment by kimci86** [comment]
Hello,
You should first check if the JPEG in the zip archive is compressed or not.
If it is compressed, the plaintext for a successful attack must be a part of the compressed data, which is hard to reconstruct without knowing a big chunk of uncompressed data.
Someone had a similar case in #18.
A known plaintext attack might be impossible in this case.

**Comment by RetiefTech** [comment]
Hi, 
Yes would be compressed with either Normal or Fastest compression level.

In #18 you mention : "Otherwise, try to find a whole file unencrypted somewhere (e.g. online or from a backup) to generate plaintext by compressing it."

Both the zipped with and without password have similar data until position 42, have found other keys using other plaintext, but still not able to re-extract the zipped with password file.

*These tests were done to figure out the way to unzip other jpegs with password protection, will continue on with john.

Thanks
