### ISSUE TITLE
Can't open files with japanese character or find items inside with japanese character

### ISSUE THREAD

**Issue by PatrickL546** [kimci86/bkcrack#37]
I have not tried with other characters. Does this only support ascii?

**Comment by kimci86** [comment]
Hello, thank you for reporting this.
Can you give more information about your issue? How can I reproduce it?
I have no issue on my machine with UTF-8 encoded special characters. What character encoding is used?

**Comment by PatrickL546** [comment]
Sorry for not including steps in the first place.

Steps to reproduce

1. Use release Release v1.3.0
2. Use this as the test file [試し.zip](https://github.com/kimci86/bkcrack/files/6766890/default.zip) Password is 123. Text file contains `thisisatestthisisatestthisisatest`
3. Enter `bkcrack.exe -C 試し.zip -c 試し.txt -p plain.txt` to cmd

![image](https://user-images.githubusercontent.com/75874561/124533318-1afaf800-dde0-11eb-9e80-943bfac356af.png)

4. Program shows `bkcrack 1.3.0 - 2021-05-22 File error: could not open input file ??.zip.`

![image](https://user-images.githubusercontent.com/75874561/124533526-77f6ae00-dde0-11eb-8ccc-c90148f42a00.png)

**Comment by PatrickL546** [comment]
Also, I was going to try the 32-bit version. It seems some anti-virus and chrome detects it as malicious but the 64-bit is clean. Don't know if you can fix that or not.
![image](https://user-images.githubusercontent.com/75874561/124534205-bfca0500-dde1-11eb-99ce-07a7a3c76317.png)
![image](https://user-images.githubusercontent.com/75874561/124534295-ee47e000-dde1-11eb-8806-4157ac5a603d.png)

**Comment by kimci86** [comment]
Great, thank you for those details.
So I had a look and found that:
- The zip entry filename is encoded in UTF-8.
- Special characters work well on Ubuntu as UTF-8 is used everywhere, both for the file name and the zip entry.
- MS Windows's console does not use UTF-8 by default, hence the issues both for the file name and the zip entry.

I am not sure how to deal with special characters on Windows. I will try to figure it out if I get the time.

**Comment by magnumripper** [comment]
From http://fileformats.archiveteam.org/wiki/ZIP:
*in general there is no official file name encoding for ZIP files, and non ASCII filenames are not generally well supported. The original implementation specified IBM Code Page 437 for filenames, but as many characters cannot be expressed in that encoding, the filename bytes have often been interpreted using the current system codepage (implementation dependent behaviour). There is a flag to specify UTF-8 as the encoding, but it is not supported in all major clients*

I found myself not being able to `-c Möller.doc` but I could work around it by using eg. `-c $(iconv <<< Möller.xls -t cp437)`.

**Comment by magnumripper** [comment]
I had this problem again and came up with an idea:

More often than not, the attacked file is the first or the only one in an archive. So how about this: If you say `-C enc.zip` but omit any `-c FILE` option, just pick the first file!

I made a partial/experimental patch and it works just fine. It boils down to this:
```diff
diff --git a/src/zip.cpp b/src/zip.cpp
index 0a9b44b..356169d 100644
--- a/src/zip.cpp
+++ b/src/zip.cpp
@@ -257,7 +257,9 @@ std::ifstream openZipEntry(const std::string& archive, const std::string& entry,
     ZipIterator it = std::find_if(locateZipEntries(is), ZipIterator(),
         [&entry](const ZipEntry& e)
         {
-            return e.name == entry;
+            if(entry.empty())
+                std::cerr << "Found file " << e.name << "\n";
+            return entry.empty() || e.name == entry;
         });
 
     if(it == ZipIterator())
```
And I also did this:
```diff
diff --git a/src/Arguments.cpp b/src/Arguments.cpp
index 37b613b..00e230c 100644
--- a/src/Arguments.cpp
+++ b/src/Arguments.cpp
@@ -44,14 +44,14 @@ void Arguments::parse(int argc, const char* argv[])
     }
     else
     {
-        if(cipherfile.empty())
-            throw Error("-c parameter is missing");
+        if(cipherarchive.empty() && cipherfile.empty())
+            throw Error("-C and/or -c parameter is missing");
         if(plainfile.empty())
-            throw Error("-p parameter is missing");
+            throw Error("-P and/or -p parameter is missing");
     }
 
-    if(!decipheredfile.empty() && cipherfile.empty())
-        throw Error("-c parameter is missing (required by -d)");
+    if(!decipheredfile.empty() && cipherarchive.empty() && cipherfile.empty())
+        throw Error("-C and/or -c parameter is missing (required by -d)");
     if(!decipheredfile.empty() && decipheredfile == cipherfile)
         throw Error("-c and -d parameters should point to different files");
     if(!unlockedarchive.empty() && cipherarchive.empty())
```

For some reason I have yet to understand, it doesn't work for the `-P` option but that one is not by far as important to implement.

**Comment by kimci86** [comment]
Indeed, choosing an entry by index instead of name would avoid encoding issues. Thank you for the suggestion. I will try to implement this soon™.

**Comment by cxzstuff** [comment]
Easiest solution is just to rename that target file (-c) within the zip file (-C).
