### ISSUE TITLE
Unable to find cipherfile with folder path

### ISSUE THREAD

**Issue by tpw1314** [kimci86/bkcrack#39]
Sample scenario : i am at drive C: with plain
zip file structure is as below IN E: drive.
e.zip
---folder1
---------e.JPG

command executed -
bkcrack -C E:\e.zip -c \folder1\e.JPG -P plain.zip -p plain

error -
Zip error : found no entry \folder1\e.JPG in archive E:\e.zip

I even try to exclude folder path and just input e.JPG - same error.
used different combination of backward slah \ or slah /, adding . at the beginning of folder path - same error.

**Comment by tpw1314** [comment]
Update : 
Found the solution to this, command should be -
bkcrack -C E:\e.zip -c folder1/e.JPG -P plain.zip -p plain.

But now i am getting different error -
[10:01:30] Could not find the keys.

But e.JPG are the same file, one zipCrypto deflate, one deflate.
This is weird. What am I doing wrong ?

It was working with different file but within same directory.
Now when i work on 2 different drive C: and E: - somehow different.

**Comment by kimci86** [comment]
Hello !
Having files on different drives or not should make no difference.
If I understand correctly, you know the image `e.JPG` but the encrypted zip archive and the plain zip archive were created with different versions of 7zip. So maybe the compression is not exactly the same for encrypted and plain files.

You first have to make sure that the image `e.JPG` is the correct one (by checking uncompressed size and CRC are the same in both zip archives) and that the compression is the same for both encrypted and plain versions (check that encrypted compressed size = plain compressed size + 12).

If you need more help, could you reply with some metadata about your files ?
i.e. showing the output of running `7z l -slt E:\e.zip` and `7z l -slt C:\plain.zip`.

**Comment by kimci86** [comment]
@tpw1314 Did you make some progress? Do you have more questions?
