### ISSUE TITLE
Could not find the keys.

### ISSUE THREAD

**Issue by mrcarl79** [kimci86/bkcrack#44]
Hi, 

Can you help, I'm following this:

https://blog.devolutions.net/2020/08/why-you-should-never-use-zipcrypto

But get "Could not find the keys." error.

This is the file I'm trying to get:

Path = vid03.mpg
Folder = -
Size = 3802041
Packed Size = 3739062
Modified = 2006-11-06 00:55:54
Created =
Accessed =
Attributes =  -rwxrwxrwx
Encrypted = +
Comment =
CRC = 9894DFB7
Method = ZipCrypto Deflate
Characteristics = up : Encrypt
Host OS = Unix
Version = 20
Volume Index = 0
Offset = 1606936819

This is the command:

bkcrack -C encrypted.zip -c vid03.mpg -P plain.zip -p plain.txt

This is the plain.zip file

Path = plain.txt
Folder = -
Size = 38
Packed Size = 38
Modified = 2021-09-02 11:22:52
Created = 2021-09-02 11:22:12
Accessed = 2021-09-02 11:37:39
Attributes = A
Encrypted = -
Comment =
CRC = D509EE84
Method = Store
Characteristics = NTFS
Host OS = FAT
Version = 10
Volume Index = 0
Offset = 0

Can you help at all?

**Comment by kimci86** [comment]
I close this as I understand you have no more questions. Feel free to reopen or open a new issue otherwise.
