### ISSUE TITLE
Support false positives

### ISSUE THREAD

**Issue by solardiz** [kimci86/bkcrack#5]
As I understand, when there's little known plaintext available the number of remaining values is large enough that false positives during the search are quite likely. In fact, pkcrack doesn't abort the search upon finding potential keys by default, having this non-default option to do so:

```
 -a     abort keys searching after first success
```

Perhaps bkcrack should do the same.

**Comment by kimci86** [comment]
I believe it is not so likely to happen (at least when the plaintext is correct) but I agree such an option can be useful. Thank you for this suggestion. I am working on it.

**Comment by kimci86** [comment]
Now implemented.
See https://github.com/kimci86/bkcrack/compare/a31ef6d475152d603acb8e177b8af6ff6da2a748...1b82756cdf1452ae4efdb6acf80d3dac888a83c3
