### ISSUE TITLE
Compress included file before running or not?

### ISSUE THREAD

**Issue by linux-mining** [kimci86/bkcrack#52]
Firstly thank you for this program I am desperate to get some files back from an old archive and I happen to have one of the files in the archive and its one of the largest files in it (Apparently that is great).

The archive is pkzip2 as verified in the zip2john utility. 

But the archive is compressed and encrypted, but I have the file uncompressed. (Not great apparently)

So it seems in this case I would need to compress the file first.

Is there a practical way to do this with various settings? How many variations of compression are there in this case? 

Also the files are in a folder in the Archive that is NOT compressed or encrypted if that helps anything.

`$ 7z l -slt L.zip

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz (906E9),ASM,AES-NI)

Scanning the drive for archives:
1 file, 375186269 bytes (358 MiB)

Listing archive: L.zip

--
Path = L.zip
Type = zip
Physical Size = 375186269

----------
Path = L
Folder = +
Size = 0
Packed Size = 0
Modified = 2016-09-15 02:13:15
Created = 
Accessed = 
Attributes = D_ drwxrwxr-x
Encrypted = -
Comment = 
CRC = 
Method = Store
Host OS = Unix
Version = 10
Volume Index = 0

Path = L/VID_20140308_102828_041.mp4
Folder = -
Size = 79917262
Packed Size = 78376503
Modified = 2015-03-09 05:02:58
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = 65EF95F9
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/VID_20140308_102752_427.mp4
Folder = -
Size = 50907473
Packed Size = 49641968
Modified = 2015-03-09 05:02:34
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = 9158C78D
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0
######### ALSO a bunch of jpg's and stuff here
`

**Comment by kimci86** [comment]
Hi,
First, you should check the file is indeed (very likely) in your archive by looking at its uncompressed size and CRC value (running `crc32 <your_file>`).
Size and CRC should be the same as 7-zip shows for that file in the archive.

Then, you have to compress the file without encryption with various settings to match what was encrypted.
One way to be reasonably sure that the compression is the right one is to check the compressed size.
Encryption adds a 12 bytes header which 7-zip includes in the Packed Size, so the goal is to have a compressed size of Packed Size - 12.

You are asking what compression settings you should try.
The first thing to do is to use the compression software you used for creating the archive (if you remember).
Assuming 7-zip, you then would try compressing your file with various compression levels: command line options `-1`, `-2`, ... to `-9`. Info-ZIP also accepts options `-1` to `-9`. Other compression software usually have a similar parameter.
This process is manual. It is not handled automatically by bkcrack (at least for now!)

If you can get the expected compressed size, an attack might very well be successful.

If you cannot get the expected compressed size, an attack might still be possible. Deflate compression produces a sequence of blocks. Even though the entire compression does not produce the expected sequence of compressed blocks, it is possible that the first block or last block matches what was encrypted. So running an attack on the first or last few hundred bytes might be successful.
The first and last blocks are interesting because we know were they are located (at the beginning or at the end) so the location (offset parameter for bkcrack) is known.
It can be interesting to inspect the compressed data you get with various compression settings using e.g. [infgen](https://github.com/madler/infgen) or just an hexadecimal editor to see if the first and last block depends much or not on the compression settings.

Also, note that using a lot of plaintext data (e.g. more than 1 MB) does not speed up the attack anyways. Thus, bkcrack uses at most 1 MB of plaintext data by default. It can be overridden with the `-t` command line option.

Finally, you might have noticed that running an attack with a large block of known plaintext does not even take a few seconds, so do not hesitate to try and run an attack even though plaintext might be wrong. It would just fail quickly.

Let me know how it goes. Do not hesitate to ask if you need more assistance.

**Comment by linux-mining** [comment]
Thank you this is a most helpful reply.

I have one additional question. I don't remember what I used to compress this with although the time period is ~ 2009-2011.

Do you happen to know what are the likely compressors? I remember somewhat using lzma setting in 7zip.

Thanks,

**Comment by kimci86** [comment]
7-zip shows Method = ZipCrypto Deflate so the compression algorithm used is Deflate, not LZMA.
(Method = Store for folder entries is not relevant as those entries do not contain any data.)
So we know deflate compression algorithm was used. 
What remains to be determined is the compression tool used and the used parameters, in particular the compression level. To determine that, you can check the compressed size produced by different tools (starting by the tool you most probably used) and different parameters.
If you do not get a perfect match on the size, you can still hope that compression behaves the same for a long enough prefix or suffix and try an attack on the first or last few hundred bytes.

**Comment by linux-mining** [comment]
Once again thank you, this is a big help. 

I'm also running a bruteforce crack on the archive with hashcat, even with a very high guess rate but I have no idea of what password I used back then.

Anyways, on to compressing this file, now I wish it were smaller, but its the only one I've got. Thanks a million times kimci86.

**Comment by linux-mining** [comment]
Ok this is really my last question as I think I have what is a good sign.

Firstly I compressed the original file 6 times using various levels of deflate in 7zip (levels 0,1,3,5,7,9). None matched the packed size -12, however level 7 was pretty close. Given this was an AVI file it didn't compress very much ~ 1%.

So I did the following(Extract first 12 bytes of each compressed file):
dd if=MVI_2156_9 ibs=12 count=1 of=9  (got the first 12 bytes of each different level).

Then did an md5sum comparison on each one, they all matched exactly:
`:~/Downloads/bkcrack-1.3.4-Linux$ md5sum 1
ffa0e68bfe09d904bd9fa4a928e33b25  1
:~/Downloads/bkcrack-1.3.4-Linux$ md5sum 2
md5sum: 2: No such file or directory
:~/Downloads/bkcrack-1.3.4-Linux$ md5sum 3
ffa0e68bfe09d904bd9fa4a928e33b25  3
:~/Downloads/bkcrack-1.3.4-Linux$ md5sum 5
ffa0e68bfe09d904bd9fa4a928e33b25  5
:~/Downloads/bkcrack-1.3.4-Linux$ md5sum 7
ffa0e68bfe09d904bd9fa4a928e33b25  7
:~/Downloads/bkcrack-1.3.4-Linux$ md5sum 9
ffa0e68bfe09d904bd9fa4a928e33b25  9
`
But I have no earthly idea how find the offset to use or format the command (Sorry I did read the guide). 
The file in question is "MVI_2156.AVI"

I don't know if this helps but here is the full output of from the 7zip l -slt L.zip (File of interest is in **BOLD**


`7z l -slt L.zip

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz (906E9),ASM,AES-NI)

Scanning the drive for archives:
1 file, 375186269 bytes (358 MiB)

Listing archive: L.zip

--
Path = L.zip
Type = zip
Physical Size = 375186269

----------
Path = L
Folder = +
Size = 0
Packed Size = 0
Modified = 2016-09-15 02:13:15
Created = 
Accessed = 
Attributes = D_ drwxrwxr-x
Encrypted = -
Comment = 
CRC = 
Method = Store
Host OS = Unix
Version = 10
Volume Index = 0

Path = L/VID_20140308_102828_041.mp4
Folder = -
Size = 79917262
Packed Size = 78376503
Modified = 2015-03-09 05:02:58
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = 65EF95F9
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/VID_20140308_102752_427.mp4
Folder = -
Size = 50907473
Packed Size = 49641968
Modified = 2015-03-09 05:02:34
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = 9158C78D
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/VID_20140308_110555_653.mp4
Folder = -
Size = 5847545
Packed Size = 5008006
Modified = 2015-03-09 05:01:24
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = 64DFD6E1
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_20141222_140406475.jpg
Folder = -
Size = 2325836
Packed Size = 2162202
Modified = 2014-12-22 19:52:24
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = 31009014
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_20141222_124113247.jpg
Folder = -
Size = 1697760
Packed Size = 1531589
Modified = 2014-12-22 19:52:24
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = 108AD508
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_20140223_182229_456.jpg
Folder = -
Size = 1071149
Packed Size = 1029638
Modified = 2015-03-09 05:01:28
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = 7E0EA0E4
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_20140223_182225_313.jpg
Folder = -
Size = 1063491
Packed Size = 1021691
Modified = 2015-03-09 05:01:08
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = ADF2AFDE
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_20140223_182230_999.jpg
Folder = -
Size = 1070928
Packed Size = 1027618
Modified = 2015-03-09 05:01:22
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = 112C4762
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_20140308_110606_887.jpg
Folder = -
Size = 793614
Packed Size = 752260
Modified = 2015-03-09 05:01:12
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = 79C6351E
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_20140223_182237_751.jpg
Folder = -
Size = 1139499
Packed Size = 1098917
Modified = 2015-03-09 05:01:10
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = E89E78DE
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_20140223_182226_832.jpg
Folder = -
Size = 1047841
Packed Size = 1003562
Modified = 2015-03-09 05:01:32
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = B70A2F39
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_20140223_182221_036.jpg
Folder = -
Size = 968408
Packed Size = 926504
Modified = 2015-03-09 05:01:16
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = C0C55379
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_0896.jpg
Folder = -
Size = 281379
Packed Size = 280414
Modified = 2014-02-26 16:25:48
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = 74202424
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_20140223_182235_565.jpg
Folder = -
Size = 1306559
Packed Size = 1266008
Modified = 2015-03-09 05:01:38
Created = 
Accessed = 
Attributes = _ -rw-rw-r--
Encrypted = +
Comment = 
CRC = A287D9B6
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

**Path = L/MVI_2156.AVI
Folder = -
Size = 190121402
Packed Size = 189662444
Modified = 2014-11-10 21:37:18
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 9A4D722E
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0**

Path = L/IMG_20150220_160226109.jpg
Folder = -
Size = 458798
Packed Size = 284886
Modified = 2015-03-09 21:23:54
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 4112A924
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_20140917_150822059_HDR.jpg
Folder = -
Size = 1196172
Packed Size = 1042864
Modified = 2014-10-02 20:33:58
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 1B36D4A2
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_2155.JPG
Folder = -
Size = 2327179
Packed Size = 2319954
Modified = 2014-09-30 20:28:22
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 7820589E
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_2154.JPG
Folder = -
Size = 2356871
Packed Size = 2352773
Modified = 2014-09-30 20:28:21
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 5C142E40
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_2153.JPG
Folder = -
Size = 2322184
Packed Size = 2317590
Modified = 2014-09-30 20:29:37
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 863D7A73
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_2152.JPG
Folder = -
Size = 2420973
Packed Size = 2416568
Modified = 2014-09-30 20:29:37
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 70B45C5A
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_2151.JPG
Folder = -
Size = 2797828
Packed Size = 2793023
Modified = 2014-09-30 20:29:37
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 413288FC
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_2150.JPG
Folder = -
Size = 2476893
Packed Size = 2469660
Modified = 2014-09-30 20:29:36
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = C9CCAF68
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_2149.JPG
Folder = -
Size = 2582386
Packed Size = 2577522
Modified = 2014-09-30 20:29:36
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 1F1EAB64
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_2148.JPG
Folder = -
Size = 2629948
Packed Size = 2625759
Modified = 2014-09-30 20:29:36
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 704E3A0C
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_2147.JPG
Folder = -
Size = 2584061
Packed Size = 2579888
Modified = 2014-09-30 20:29:35
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 91B26BCC
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_2146.JPG
Folder = -
Size = 2583322
Packed Size = 2579177
Modified = 2014-09-30 20:29:35
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 55C3DC92
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_2145.JPG
Folder = -
Size = 2419775
Packed Size = 2415570
Modified = 2014-09-30 20:29:35
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 5567DBE1
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_2144.JPG
Folder = -
Size = 3078423
Packed Size = 3074568
Modified = 2014-09-30 20:29:34
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 8C49157F
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_2143.JPG
Folder = -
Size = 2542998
Packed Size = 2539066
Modified = 2014-09-30 20:29:34
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = D666A923
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_2142.JPG
Folder = -
Size = 3438801
Packed Size = 3434702
Modified = 2014-09-30 20:29:34
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 950CC03B
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0

Path = L/IMG_2118.JPG
Folder = -
Size = 2571418
Packed Size = 2567267
Modified = 2014-09-30 20:29:26
Created = 
Accessed = 
Attributes = _ -rwx------
Encrypted = +
Comment = 
CRC = 430E8256
Method = ZipCrypto Deflate
Host OS = Unix
Version = 20
Volume Index = 0
`

**Comment by kimci86** [comment]
> GOT IT AFTER 10 YEARS OF TRYING!!!!!!!

Very good! :tada:
I edited your comment above to remove the internal keys as it can be used to recover (with great effort) your password, that you might not want to share.

> I have 2 more archives with the same password but I'm not so lucky to have a matching file.
> [...]
> Or can I use the same keys on the other archives?

When the same password is used, there is no need for another attack. The internal keys are the same.
With the result of your successful attack, you can generate archives with a password of your choice as you did with the first archive.

    ./bkcrack -C other_archive.zip -k <X> <Y> <Z> -U other_archive_new.zip whatever

bkcrack does not check the integrity of the generated archive. It can be bad if the original password was not as expected. You can make sure everything is right with e.g.:

    7z t other_archive_new.zip

and type the chosen password when prompted (`whatever` is my example above).

---

> Hashcat has a pkzip "master key" mode for recovering passwords (I'm pretty sure this is a long one) on the GPU. Do you happen to know how I can generate a "master key"

Hashcat expect the concatenation of the three components bkcrack gives. Just remove spaces and you have the master key for hashcat. For example `c4490e28b414a23d91404b31` (Example from the tutorial for password `W4sF0rgotten`.)

bkcrack can also be used to recover passwords. I found an optimization which makes it about as fast as hashcat on my 10 years old GPU (only 96 CUDA cores...). I hope to eventually contribute this optimization to hashcat as well.

Anyways it still takes ages for complex passwords. That will be useful only if you really want to know what was your password. It is not needed to recover your data.

---

> I tried running the following command:
> $ ./bkcrack -c L.zip -p test.zip
> [...]
> Do I need an offset or something, sorry I'm still lost

Using `-c` and `-p` parameters without `-C` and `-P` is a little more advanced.
`-c` alone it is to use encrypted data that you got out of a zip file yourself and put into a file on its own.
`-p` alone is to use data you compressed or forged somehow without making a zip file.
The simpler usage is with `-P` and `-C`. Then `-c` and `-p` parameters correspond to entries in zip files.

---

I am glad it worked out!
If you have any feedback to improve bkcrack, do not hesitate to share it.
Feel free to open issues on github. Pull requests are welcome too.

Do you have more questions?

**Comment by linux-mining** [comment]
Thank you for your help kimci86, without it I wouldn't have figured it out. These files had a bunch of family and friends pictures and I have no idea why I ever even encrypted it in the first place. 

I also wanted to add for anybody who may stumble upon this post that none of about a hundred options in 7zip deflate would give me the right compressed size however my first try with Info-ZIP -6 (level six) worked.

**Comment by kimci86** [comment]
> Also concerning the speed of your password recovery it appears to be much faster than you think. Using hashcat on a RTX 3060 (thousands of CUDA cores) appears to be about the same speed as my CPU at least from a preliminary test.

Oh right, I remember now haschat was unbearably slow on my old GPU and about as fast as bkcrack on a testing environment with a good GPU.

> I have now recovered all 3 volumes as expected without issue, so perhaps its best to close this. Again thank you!

Good! :tada:
