### ISSUE TITLE
Bkcrack corrupted ZIP archive

### ISSUE THREAD

**Issue by Saicopate** [kimci86/bkcrack#57]
Hi, 
I have a large zip archive with my photos that I am trying to decrypt with bkcrack as I am not sure with the password.

7-zip sees the archive structure and most of the files inside (but not all).
I have one unencrypted jpeg that I was able to compress (with deflate) to the same size as the one in the archive (-12 bits for encryption).
But when I try to use bkcrack with command:
`bkcrack.exe -C photos.zip -c Zdjęcia\folder\photo1.jpg -P photo1.zip -p photo1.jpg -t 64`
it says:

`Zip error: found no entry Zdjŕcia\folder\photo1.jpg in archive photos.zip.`

I suspect it has something to do with zip corruption. Maybe this is also the reason why I cannot extract the archive with the password that I suspect might be the right one? Or is a matter of using Polish letters in zipped folder name?

The archive is quite large (11Gb). Is there a way to separate this one file to work on it instead of working on the whole archive?
I tried to use Zip2Fix but run out of memory.. So currently I have no clue how to proceed with this. Any help appreciated.

**Comment by kimci86** [comment]
Hello,
I think the error occurs because the non-ASCII character ę is encoded differently by your command line interpreter and by the zip creation tool which was used.
I am not sure how to make this work on Windows. Someone already reported a similar issue #37. It works on other operating systems where UTF-8 encoding is used by default.
A workaround, not yet implemented, would be to accept a numeric index instead of a name to specify which entry to load.
In the meantime, you can try to rename the entry with an archive manager so that the file name contains only ASCII characters.
Does that work for you?

**Comment by Saicopate** [comment]
Hi. Much thanks for your support! 

Unfortunately the option to rename the folder within the archive is grayed out in 7-zip. 

That may have something to do with archive corruption (headers). Is there a way to specify this file not by name but with e.g. its offset? 

Or maybe somehow extract this file from the whole archive to a separate one, rename it and then use bkcrack?

**Comment by kimci86** [comment]
> Is there a way to specify the known file not by name but with e.g. its offset?

It is not yet implemented, but I will add this option, hopefully soon.

What you can do already is to open the archive in an hexadecimal editor, find the encrypted data and save it into a new file. Then use this file with bkcrack.
Be careful not to edit your archive when doing so. Maybe make a backup.
That requires to know what to look for. See this [ZIP (file format) - Wikipedia](https://en.wikipedia.org/wiki/ZIP_(file_format)#Local_file_header) to learn about the format.

If it looks too technical, you can try to rename the entry with another archive managers than 7-zip or wait that I improve bkcrack to be able to specify an entry by index.

**Comment by cxzstuff** [comment]
> The archive is quite large (11Gb). Is there a way to separate this one file to work on it instead of working on the whole archive? 
Try WinZip. Rename the achive something else than .zip , like .bak so it doesn't try to exctract the zip file first asking for password... maybe it can rename that folder too??

**Comment by Saicopate** [comment]
Hi guys, thanks for your support. What I did is I extracted the single image file from the encrypted zip archive with HxD and run bkcrack attack on it with "-c" option as kimci86 suggested but found no keys.
Would you have a look - I attach here 3 versions of the the same image: original, deflated (zip) and encrypted (zip). All CRC matching. https://we.tl/t-D48f0uY6Ou

**Comment by kimci86** [comment]
I manually removed zip metadata at the begining of "encrypted.zip" file do get ciphertext and run
`bkcrack -c ciphertext -P deflated.zip -p dali_atomicus_philippe_halsman.jpg -r 12 ?p`
Two and a half seconds later, the password is 123QWErty

**Comment by Saicopate** [comment]
Great! Thank you a lot Kimci! You made my day! :-D I owe you a beer.

Ps. Password was one time, no worries :-)
