### ISSUE TITLE
Question: Determining offset of file

### ISSUE THREAD

**Issue by nixklai** [kimci86/bkcrack#59]
Let's say I have a [vulnerable zip file](https://github.com/kimci86/bkcrack/files/8191141/Example.zip). 

A procedure I follow:
1. I opened the zip file in 7-Zip
2. Search for files with compression-encryption combination `ZipCrypto Store`.
3. Attack a file with said combination file with `-c` and `-p` arguments.

However, I stumbled upon a problem. Like in the attached `Example.zip` file, the zip file path contains non-English characters (in this case, Chinese characters). Specifying the file to attack failed, likely due to those characters.

Therefore, I would like to attack the zip file via an offset. By opening the file in 7-Zip, I noticed the offset for a file "tick.png" is `181` and passed the argument `-o 181`.
Is it the correct way to determine the offset? I tried the following arguments to no avail:
```
C:\bkcrack\bkcrack-1.3.4-win64>bkcrack.exe -c Example.zip -o 181 -p tick.png
...

C:\bkcrack\bkcrack-1.3.4-win64>bkcrack.exe -c Example.zip -o 0xb5 -p tick.png
bkcrack 1.3.4 - 2022-01-01
[01:35:14] Z reduction using 2143 bytes of known plaintext
100.0 % (2143 / 2143)
[01:35:15] Attack on 438 Z values at index 190
100.0 % (438 / 438)
[01:35:16] Could not find the keys.
```

(The `Example.zip` file Password is `password`, FYI).

**Comment by kimci86** [comment]
Hello,

> Is it the correct way to determine the offset?

No, the offset parameter is not used to specify where the ciphertext starts. It is used to specify where the given plaintext starts relative to ciphertext (without encryption header). It is useful when the known plaintext is not the beginning of the encrypted file or zip entry. The offset parameter is not a solution to your problem.

> Specifying the file to attack failed, likely due to those characters.

Yes, the problem here is that non-ASCII characters are not handled correctly on Windows.
This problem was reported (#37, #57). I created a patch recently that should solve it, see #58. I will merge it soon.
Could you you confirm that this solution #58 works for you?

Even when #58 gets merged, specifying which entry to load by index rather than by name could be useful. I will implement that in the future.

**Comment by nixklai** [comment]
Thank you for your clarification! 

After double-checking, I realised the zip file I am trying to recover is actually encoded in [Big5](https://en.wikipedia.org/wiki/Big5), so the `Example.zip` I created is not exactly correct.

PR #58 unfortunate does not work. Please see the console output below:

```
C:\bkcrack\>bkcrack.exe -C "C:\bkcrack\Example.zip" -c "1上A/tick.png" -p PNG_PREFIX -x -1 54
bkcrack 1.3.4 - 2022-02-23
Zip error: found no entry 1銝_20210318/tick.png in archive C:\bkcrack\Example.zip.
```

**Comment by kimci86** [comment]
Indeed, if the entry name is not UTF-8 encoded inside the zip file, it will not work.
A workaround on linux would be to use `iconv` like so:
```
bkcrack -C Example.zip -c $(iconv -t big5 <<< "1上A_20210318/tick.png") -p PNG_PREFIX
```
I don't know if there is an equivalent on Windows.
Anyways, it confirms that specifying an entry by index can be useful.

----

By the way, `-x -1 54` is wrong for the example file you provided. The file `tick.png` has a CRC value of C1F0068B (and bit 3 of the general purpose bit flag is not set) so the check byte is C1. You can use `-x -1 c1`.

**Comment by nixklai** [comment]
I forgot the change the CRC value to the `Example.zip`. My bad 😅
I tried the `iconv` method on Ubuntu on WSL, but a new error popped up:

```
$ bkcrack.exe -C BK.zip -c $(iconv -t big5 <<< "1上A/story.png") -p PNG_PREFIX
bkcrack 1.3.0 - 2021-05-22
Arguments error: expected a flag, got ???y??/tick.png.
Run 'bkcrack -h' for help.
```

I believe the `$(iconv ...)` output is incorrectly interpreted and resulted in the error. I believe #60 is likely the only reliable way to handle this type of file.

Many thanks to @kimci86 for your help!
