### ISSUE TITLE
CP: unable to get the file status (STAT) of 'bkcrack': there is no file or directory

### ISSUE THREAD

**Issue by Dr34nn** [kimci86/bkcrack#63]
/desktop/bkcrack
cp bkcrack /usr/sbin/bkcrack

**Comment by kimci86** [comment]
Hello,
Could you explain precisely what you are trying to do and what you tried already?
I suspect you did not run `cp` from the right working directory.
Also, `/usr/sbin` folder is for system administration utilities. If you want to install bkcrack on your system, I recommend installing the executable into `/usr/local/bin` instead.

**Comment by kimci86** [comment]
I close this in the absence of feedback.
