### ISSUE TITLE
Is it possible to have an alternative way to input the -c parameter?

### ISSUE THREAD

**Issue by asdfrewq1123** [kimci86/bkcrack#71]
I have successfully run the tutorial, but now I'm trying to use it to decrypt a file with none-ASCII character in the name of comperssed file, and I have encountered some encoding issues which make it impossible to put the filename into the console.
Is it possible to have an alternative way to input the -c parameter, for example, in sercet.zip, where we get

    Index Encryption Compression CRC32    Uncompressed  Packed size Name
    ----- ---------- ----------- -------- ------------ ------------ ----------------
        0 ZipCrypto  Deflate     7ca9f10a        54799        54700 advice.jpg
        1 ZipCrypto  Store       a99f1d0d         1265         1277 spiral.svg
and use the index 1 instead of inputing `spiral.svg`?

**Comment by kimci86** [comment]
Hello,
Yes, you can use `--cipher-index` followed by the index of the entry you want.
For example, `--cipher-index 1` corresponds to `-c spiral.svg` in the `secrets.zip` archive.

**Comment by kimci86** [comment]
I close this issue as your question have been answered. Feel free to reopen if I am mistaken.
