### ISSUE TITLE
Exact length of password

### ISSUE THREAD

**Issue by mrCabez** [kimci86/bkcrack#72]
Is there any way to search for an exact length without starting from zero?
Example: I'm trying to discover a 21 characters length password.
Thanks

**Comment by kimci86** [comment]
Hello,
That is not implemented at the moment, but it would be nice to have. Thank you for the suggestion. I hope to improve password recovery with solutions for issues #34, #35 and #55 eventually.
Let us keep this issue open until it is implemented.

**Comment by kimci86** [comment]
Fix has been released in version 1.6.0
