### ISSUE TITLE
Remove ZIP archive encryption

### ISSUE THREAD

**Issue by A-Kazak** [kimci86/bkcrack#74]
Greetings!

  Actually this is not an issue, but a feature request.
  It would be great if -U could accept an empty password and output a ZIP archive fully unlocked, that is without password at all.

Does this make sense?

**Comment by kimci86** [comment]
Hi,
I agree that would be nice, but it is not so simple to implement.
Removing encryption changes the ZIP file structure because encryption headers are removed, so entry offsets have to be updated in the archive metadata. That is surely feasible but requires some implementation effort. It was much simpler to implement password changing, which does not change the ZIP file structure at all.
Maybe it will come in a future version. Thank you for the suggestion.

**Comment by A-Kazak** [comment]
Got it!

Currently bkcrack can extract a taking the known keys.
However, I do not see a straight way, except to compose a batch script parsing the input file-folder archive structure and extract each items one-by-one.
Is there a way to extract whole archive to a specified folder, for example named after the input archive file name?

**Comment by kimci86** [comment]
A simple solution to extract every entries is to change the archive password (to be precise, create an archive with the same content but encrypted with the password of your choice) with the -U option, then use any ZIP file utility such as 7zip to extract the new archive, passing the chosen password when prompted.

**Comment by A-Kazak** [comment]
> A simple solution to extract the whole archive is to change the archive password (to be precise, create an archive with the same content but encrypted with the password of your choice) with the -U option, then use any ZIP file utility such as 7zip to extract the new archive, passing the chosen password when prompted.

Got it!
Thanks.

**Comment by swiftgeek** [comment]
One more use case for this: having two archives, one with known password and other with unknown one, compressed by the same but unknown app, with a common file shared between them. Once known one has encryption stripped it could be used as `plain.zip`

**Comment by kimci86** [comment]
@swiftgeek Agreed, that would be convenient.
Note that for that specific example you describe, it is already possible to decipher (without decompressing) the common file from the archive with known password (using option -d) and then use that deciphered data as know plaintext (using option -p).

**Comment by swiftgeek** [comment]
Ah was missing c4aad9372eb4577d187d9ce43849b15927d5a156 which adds `--password`, thanks
