### ISSUE TITLE
Specify characters that will be used in password recovery

### ISSUE THREAD

**Issue by puujee12** [kimci86/bkcrack#78]
Hello, I was wondering that, is it possible to specify characters that will be used in password recovery? I'm trying to recover password with 28 length and I know that this password uses Decimals and upper-case Hexadecimal characters only. Even though there is ?u?d option it will take very long time.

**Comment by kimci86** [comment]
Hi, yes you can specify a character set explicitly as a list of characters. Sequences with a questions mark are shortcuts.
For uppercase hexadecimal digits, you can use `0123456789ABCDEF`, or in short `?dABCDEF`.

**Comment by puujee12** [comment]
Thank you very much for your fast reply and incredible tool xD

**Comment by kimci86** [comment]
With the current version on master branch (build artifacts [available here](https://github.com/kimci86/bkcrack/suites/8179281216/artifacts/355662656)), you can use:
<code>bkcrack -k <i>X Y Z</i> --bruteforce ?dABCDEF --length 28</code>

**Comment by kimci86** [comment]
Note that exploring this search spaces of $16^{28} \approx 5.19\times10^{33}$ candidates will takes a few billions years.
