### ISSUE TITLE
More precise set of characters for password recovery

### ISSUE THREAD

**Issue by dkdlv** [kimci86/bkcrack#80]
Hi!
On the same idea to improve the password finding ( #72 ), is it possible to find a way to give a more precise set of characters? 

Maybe on the way John let us give a regex: in my case, I am seaching an uppercase hexadecimal string so being able to give something like that in entry [A-F0-9] should be more efficient on long passwords. 

Thanks!

**Comment by kimci86** [comment]
Hi,
You can specify characters to use by listing them explicitly. Using predefined character sets such as `?p`, `?l`, etc is not mandatory. In the case of uppercase hexadecimal digits, you can use `0123456789ABCDEF`, or in short `?dABCDEF` as the character set.
Being able to use a regex could be nice especially once masks are supported (#55), but it will take me some time to implement it.

For the record, a similar question was asked in #78.
Maybe this deserves some more documentation or a more detailed example in the tutorial.
