### ISSUE TITLE
Is bkcrack only for attack on zip file? Can it be binary file (not depends on any type)

### ISSUE THREAD

**Issue by fitrarhm** [kimci86/bkcrack#82]
Sory for asking this. But when i read the slogan "Crack legacy zip encryption with Biham and Kocher's known plaintext attack.", i assume **bkcrack** only work for Zip file with spesific condition (zipcrypto etc). But when, i read the command line help instruction, i found that there frase that indicate bkcrack can be used for any file which is :

 " -c, --cipher-file <file>    **Zip entry** or **file on disk containing ciphertext**"
" -p, --plain-file <file>     **Zip entry** or **file on disk containing plaintext**"

So, what i'm gonna do is **Bcrack** can be used for another to attack ciphertext which is not Zip file, where in my case is a TXT & BIN file (without any file extentions).

![image](https://user-images.githubusercontent.com/63356065/200114245-8e040b37-fe9d-4ef7-907e-488b1a89a264.png)

I have try using this command for that, so is this really can be used for any kind ciphertext file type?

`bkcrack --cipher-file ciphertext --plain-file plain37
`

Thank you.

**Comment by kimci86** [comment]
Hello, bkcrack only works with ciphertext generated by traditional PKWARE encryption (also known as ZipCrypto). It does not work with any other encryption algorithm.
This kind of ciphertext is usually found in Zip archives. This is why the usual and convenient way to use bkcrack is to pass it a Zip archive from which ciphertext is loaded: it reads metadata from Zip archive, deduce from it which part of the archive is ciphertext and loads that part. But it is not technically required to get ciphertext from within a Zip archive. In theory, a user could have ciphertext from something else. It is then possible to save ciphertext in a file on its own and pass it to bkcrack.

**Comment by fitrarhm** [comment]
Thank you for you explanation.
