### ISSUE TITLE
Is it possible to speed up original password recovery by using several archives

### ISSUE THREAD

**Issue by mastereworm** [kimci86/bkcrack#90]
Having several archives encrypted with the same password, I can get several sets of keys. Is there a theoretical possibility to speed up original pass recovery with more than one set of keys?

**Comment by kimci86** [comment]
Archive encrypted with the same password should give the same internal password representation (the three 32-bit integers X, Y, Z).
So having several archives encrypted with the same password make no difference for that matter.

**Comment by mastereworm** [comment]
It means that these keys revealed from single encrypted archive can be used to unpack all other packed with the same pass. Wow, it's totally awesome!!

**Comment by kimci86** [comment]
> It means that these keys revealed from single encrypted archive can be used to unpack all other packed with the same pass. Wow, it's totally awesome!!

Yes, that is right!

I close this as your question is answered. Thank you for your interest feedback. Do not hesitate to open other issues if you have more questions or suggestions.
