### ISSUE TITLE
Idea for improvement

### ISSUE THREAD

**Issue by marcelomacruz** [kimci86/bkcrack#97]
Hello, kimci86. How are you?

I would like to suggest a feature: a lot of times the user have have ate least one file unencrypted that are encrypted inside the encrypted zip file. The biggest problem is find the correct software (windup / winder / etc) + version of the software + compression level used (fast, normal, etc).

We know that the encrypted compressed file should have 12 bytes more than the unencrypted file compressed with the same software + version + compression level.

Is it possible to create a function or utility where the user enters the unencrypted file and multiple libraries are used to try to find a match?

Thank you very much for your amazing job. :)

**Comment by User1818183** [comment]
You can crack password without knowing software version. You can use first byte archive signature, datestamp  and byte  at the end of archive.  Post link for archive

**Comment by kimci86** [comment]
@User1818183 Not sure what you mean. Is it related to the suggested idea?

**Comment by User1818183** [comment]
Sorry. My bad
