### ISSUE TITLE
Use internal keys instead of password to create archive

### ISSUE THREAD

**Issue by KaDw** [kimci86/bkcrack#98]
Thanks to bkcrypt I have the files unzipped. I know that password is 16 bytes long and unfortunately it will take a lot of time for me to crack it (even with 6 bytes optimization). I would like to zip the file again and keep the same password. Is this even possible if we only know internal keys?

The usecase is that I have a config file for an old game that is stored in password protected archive. I have to unzip this archive, modify one of the files and zip it again with the same password. I could get the password by reverse engineering the game itself but I'm looking for a more generic solution

**Comment by kimci86** [comment]
Hello, your usecase looks similar the one described in another issue. See my answers there https://github.com/kimci86/bkcrack/issues/65#issuecomment-1142536511
Let me know if it helps.
